spring:
  cloud:
    gateway:
      routes:
        - id: login-service
          uri: lb://LoginService
          predicates:
            - Path=/api/users/**
          filters:
            - RemoveRequestHeader=Authorization
        - id: order-service
          uri: lb://OrderService
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://PaymentService
          predicates:
            - Path=/api/payments/**
        - id: default-service
          uri: http://8081
          predicates:
            - Path=/**

jwt:
  secret: TzUwsEvGnlBVqDaXUqJQWLtKDyZUcoccWYLL3pKbUn4=y

server:
  port: 8080
