spring:
  cloud:
    gateway:
      routes:
        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/api/login/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
        - id: default-service
          uri: http://localhost:8081
          predicates:
            - Path=/**
jwt:
  secret: TzUwsEvGnlBVqDaXUqJQWLtKDyZUcoccWYLL3pKbUn4=y

server:
  port: 8080
