spring:
  cloud:
    gateway:
      routes:
        - id: login-service
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/api/login/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
        - id: default-service
          uri: http://<fallback-uri>
          predicates:
            - Path=/**
jwt:
  secret: my-secret-key
